### ISSUE TITLE
Test are failing on Safari 10.1

### ISSUE THREAD

**Issue by JacoBotha** [IjzerenHein/autolayout.js#22]
After the latest update to safari, tests are failing in the attribute section

**Comment by IjzerenHein** [comment]
Yikes!

Will have a look shortly, very busy at the moment.

**Comment by IjzerenHein** [comment]
Just tested it on Safari, Version 10.0.3 (12602.4.8), still works perfectly on there. Haven't updated my system to the latest updates though. Will do that now and see whether that breaks anything.

**Comment by IjzerenHein** [comment]
Just tested in on Version 10.1 (12603.1.30.0.34), also runs without errors on that.
What version are you testing it on?

**Comment by JacoBotha** [comment]
Just tested it again still failing on my side
<img width="1679" alt="screen shot 2017-04-09 at 9 54 56 am" src="https://cloud.githubusercontent.com/assets/1842742/24835753/b07d8b86-1d0a-11e7-9bf2-c97e1e34fbb5.png">

**Comment by IjzerenHein** [comment]
You're right, I just retested and now it's also failing on my system. Wth, must have accidentally messed up the last test.
Will take a look, may take a while due to the high workload atm

**Comment by JacoBotha** [comment]
Thanks!

**Comment by IjzerenHein** [comment]
Hi, I did some quick tests and the problem appears to be in the Cassowary.js code. I tested with the kiwi version and that does work (dist/autolayout.kiwi.js).

Unfortunately the Cassowary.js lib is not being maintained anymore by its original author. The code is a bit of a mess to be honest, which was also one of the reasons of adding the kiwi version. I recommend using the kiwi version instead. I'll have a closer look on how to address this issue in the future. As for the kiwi version, it's actually faster than the cassowary.js version. The only drawback is, is that it doesn't support unambiguous layouts. This means that your vfl/constraints need to be "clean" and otherwise you may get exceptions. Hope this helps a bit.

**Comment by JacoBotha** [comment]
Thanks, we have gone with using the kiwi version for now
